### PR TITLE
Added Accordion Gradio to keep the UI Style

### PR DESCRIPTION
**Pull request by ernestleft**
Minimum changes were made to maintain the visual aesthetic of other scripts using Accordion in Gradio.

### CODE REVIEW

**Comment by aleksusklim** [comment]
You think?

OK, accepted.

By the way, do you happen to know how to properly define mouseover hints for extensions-created UI elements?
I implemented them hacky way, definitely not correct (at least, they don't support translation to other languages currently; and I don't have a clue how to make them localizable!)

I believe `titles` array appears to be global, so we can append stuff, aren't we?
But how in the world I would avoid messing with other people controls, if keys are literal control text, and not some internal ID?

That's why I made all my texts prefixed, to have no collisions with other hints. But that feels wrong…

**Comment by aleksusklim** [comment]
Hmm, when I tried updating my copy, all of radiobuttons under the new accordion were "disabled"!
I mean, disabled as controls, grayed-out, impossible to click.

Then I removed the extension folder manually and installed it again, getting this warning in stdout:
```
Warning: Bad ui setting value: customscript/conditioning-highres-fix.py/txt2img/Conditioning Highres.fix strength (for sd-v1-5-inpainting)/value: Cond.fix: Disabled; Default value "Cond.fix: Disabled (none)" will be used instead.
```

After that, everything is working correctly.
But I have rather outdated WebUI.

I hope people would try deleting and reinstalling too, if they ever got the same bug.

**Comment by ernestleft** [comment]
Not very expert in Python either (I mainly write in C#), but I took as an example how they implemented Accordion in other extensions in Gradio, and to maintain consistency I made the modifications. If you like, I can check how they implement translations. I use my UI in English, so I don't really notice if there are scripts with localizable labels, but if you give me an example of one that does, would be happy to take a look. 

About second thing, would you like me to change the names to match the last saved in the configuration? didn't happen to me when I made the change in my running webUI, but I think the solution would be to match the value names with the same script values before the change.

**Comment by aleksusklim** [comment]
I didn't understand which "value names" are you talking about (I thought it somehow saved my currently selected radiobutton to config and tried to restore it unsuccessfully, reverting to default which is good). Aren't they are the same? Or they are now namespaced by accordion?

I also used other extensions as the example earlier, before the same accordion fix: https://github.com/dfaker/SD-latent-mirroring/pull/6
I didn't watch closely for the WebUI development recently, but I have drafts for at least two my other extensions which I plan to publish when I finish them.
So I want to know how things should be done properly ))

**Comment by ernestleft** [comment]
Because of the error output saying last saved config was "Cond.fix: Disabled" and the new one is "Cond.fix: Disabled **(none)**"  thought the error referred to the fact that I had unknowingly changed the value name by adding " (none)", but now that I review the commit history files, I see that the values are indeed the same, perhaps the parentheses are interpreted in such a way that the value is different despite being the same?

I looked at the extension you mentioned in the link, but they used exactly the same approach that I used to add the Accordion to the UI in this script, and as for localization, I don't see that the mentioned script does any localization, it's a simple label containing the name.

In the past few days they have been making quite important changes to the UI.

If you find a script that uses language localization, let me know so I can check how they do it and anything I can help with.

**Comment by aleksusklim** [comment]
> I don't see that the mentioned script does any localization

Nor did I, that why I'm asking!

**Comment by klimaleksus** [comment]
Oh my god, github gone insane.

**Pull request merged**
